import Head from "next/head";
import React, { useState } from "react";
import useMediaQuery from "@mui/material/useMediaQuery";
import Box from "@mui/material/Box";

import NavBar from "./NavBar";
import SideBar from "./SideBar";

type TLayoutProps = {
  children: React.ReactNode;
};

const Layout = ({ children }: TLayoutProps) => {
  const isNonMobile = useMediaQuery("(min-width: 600px)");
  const [isSideBarOpen, setIsSideBarOpen] = useState(true);

  return (
    <>
      <Head>
        <title>MyDashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/business-report.png" />
      </Head>
      <Box display={isNonMobile ? "flex" : "block"} width="100%" height="100%">
        {isSideBarOpen && (
          <SideBar
            isNonMobile={isNonMobile}
            isSidebarOpen={isSideBarOpen}
            setIsSidebarOpen={setIsSideBarOpen}
          />
        )}
        <Box sx={{ flexGrow: 1 }}>
          <NavBar setIsSideBarOpen={setIsSideBarOpen} />
          {children}
        </Box>
      </Box>
    </>
  );
};

export default Layout;
